spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 828869351024-4b3mefodfksotddch8mkiha71t2tn83j.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8080/oauth2/callback"
            scope: email, profile
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
