services:
  database:
    container_name: database
    image: postgres
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "StopnShop"
      POSTGRES_PASSWORD: "123123123"
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/public/userUploads:/app/public/userUploads
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - database
      
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./frontend/public/userUploads:/app/public/userUploads
    ports:
      - "3000:3000"
    depends_on:
      - backend
      
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf