package com.example.backend.model;

public enum ReportReason {
    SPREADING_FALSE_INFORMATION,
    HARASSMENT_OR_BULLYING,
    HATE_SPEECH,
    SPAM_OR_SCAM,
    IMPERSONATION,
    PRIVACY_VIOLATION,
    INAPPROPRIATE_CONTENT,
    MISLEADING_ADVERTISING,
    DANGEROUS_ACTS_OR_CONTENT,
    CHILD_ENDANGERMENT,
    SELF_HARM_OR_SUICIDE_CONTENT,
    OTHER
}
